[
    {
        "name":"User From",
        "type":"form",
        "resource":"/user",
        "data":[
            {
                "name":"id",
                "type":"Text"
            }
        ]
    },
    {
        "name":"Job Form",
        "resource":"/jobs",
        "data":[
            {
                "name":"id",
                "type":"Number"
            },
            {
                "name":"jobName",
                "type":"text"
            },
            {
                "type":"boolean"
                "name":"finished",
            }
        ]
    }
]
